/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package parkhaus;

/**
 *
 * @author Simon
 */
public class DatenUebersicht extends javax.swing.JPanel {

    /**
     * Creates new form DatenUebersicht
     */
    public DatenUebersicht() {
        initComponents();
    }

    public boolean aktualisieren() {
        if (MainClass.getParkhaus() != null) {
            Parkhausname_text.setText(MainClass.getParkhaus().getParkhaus_Name());
            Stellplaetze_text.setText(String.valueOf(MainClass.getParkhaus().getStellpleatze()));
            Hoehe_text.setText(String.valueOf(MainClass.getParkhaus().getHoehe_in_cm()));
            stpl_laenge.setText(String.valueOf(MainClass.getParkhaus().getSummeAllerLaengen()));
            return true;
        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        stellplaetze = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Parkhausname_text = new javax.swing.JLabel();
        Stellplaetze_text = new javax.swing.JLabel();
        Hoehe_text = new javax.swing.JLabel();
        stpl_laenge = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        name.setText("Parkhausname:");
        name.setMaximumSize(new java.awt.Dimension(53, 14));
        name.setMinimumSize(new java.awt.Dimension(53, 14));
        name.setPreferredSize(new java.awt.Dimension(53, 14));

        stellplaetze.setText("Stellplätze:");

        jLabel1.setText("Höhe in cm:");
        jLabel1.setMaximumSize(new java.awt.Dimension(53, 14));
        jLabel1.setMinimumSize(new java.awt.Dimension(53, 14));
        jLabel1.setPreferredSize(new java.awt.Dimension(53, 14));

        jLabel3.setText("Länge aller Stpl:");
        jLabel3.setMaximumSize(new java.awt.Dimension(53, 14));
        jLabel3.setMinimumSize(new java.awt.Dimension(53, 14));
        jLabel3.setPreferredSize(new java.awt.Dimension(53, 14));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(name, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(stellplaetze, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Parkhausname_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Stellplaetze_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Hoehe_text, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                    .addComponent(stpl_laenge, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Parkhausname_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Stellplaetze_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stellplaetze, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(Hoehe_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(stpl_laenge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 11, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Hoehe_text;
    private javax.swing.JLabel Parkhausname_text;
    private javax.swing.JLabel Stellplaetze_text;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel name;
    private javax.swing.JLabel stellplaetze;
    private javax.swing.JLabel stpl_laenge;
    // End of variables declaration//GEN-END:variables
}
